[package]
name = "crossroad_server"
version = "0.1.0"
authors = ["Rutger Schoorstra <schoorstra_rutger@hotmail.com>"]

[dependencies]
serde = "0.9.6"
serde_json = "0.9"
serde_derive = "0.9.6"
schedule_recv = "0.0.1"
time = "0.1.32"
itertools = "0.4.1"
permutohedron = "0.1.7"
clap = "1.5.3"
