version: "3"

services:
 crossroad_server:
  build: .
  command: ["run", "localhost"] 
  ports:
   - "9990:9990"
  network_mode: "host"

 websocketify:
  build: docker-websockify/.
  entrypoint: "./run"
  command: ["9080", "localhost:9990"] 
  ports:
    - "9080:9080"
  container_name: websockify
  network_mode: "host"

